---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: docker-registry
spec:
  selector:
    app: registry
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443

